# Generated by Django 6.0.4 on 2026-05-30 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Password (Hash)')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Peran')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('no_telepon', models.CharField(blank=True, default='', max_length=20, verbose_name='No. Telepon')),
                ('alamat', models.TextField(blank=True, default='', verbose_name='Alamat')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='pengguna/foto/', verbose_name='Foto Profil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dibuat Pada')),
                ('diperbarui', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Pengguna',
                'db_table': 'data_entry_pengguna',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=500, verbose_name='Judul Artikel')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Dibuat')),
                ('set_view', models.CharField(choices=[('publish', 'Publish'), ('not_publish', 'Not Publish')], default='not_publish', max_length=20, verbose_name='Status Publikasi')),
                ('article', models.TextField(verbose_name='Isi Artikel')),
                ('kategori', models.CharField(choices=[('teknologi', 'Teknologi'), ('sains', 'Sains & Riset'), ('bisnis', 'Bisnis & Manajemen'), ('tutorial', 'Tutorial & Panduan'), ('berita', 'Berita & Update'), ('lainnya', 'Lainnya')], default='teknologi', max_length=50, verbose_name='Kategori')),
                ('ringkasan', models.TextField(blank=True, default='', verbose_name='Ringkasan')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='content/thumbnail/', verbose_name='Thumbnail')),
                ('tags', models.CharField(blank=True, default='', max_length=300, verbose_name='Tags (pisah dengan koma)')),
                ('view_count', models.IntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('diperbarui', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diperbarui')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='data_entry.pengguna', verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Konten',
                'verbose_name_plural': 'Konten',
                'db_table': 'data_entry_content',
                'ordering': ['-date_created'],
            },
        ),
    ]
